name: Build .NET API

on:
    push:
        branches: [main]
        paths:
            - "./src/**"
    pull_request:
        branches: [main]
        paths:
            - "./src/**"
    workflow_dispatch:

defaults:
    run:
        working-directory: ./src

jobs:
    build-unittest:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                operating-system: [ubuntu-latest]
                dotnet-version: ["6.0"]
        steps:
            - name: Checkout GitHub Action
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x

            - name: DotNet Restore Packages
              run: dotnet restore

            - name: DotNet Build
              run: dotnet build --no-restore

            - name: DotNet Unit Test
              working-directory: ./src/DotNet6API_Sample.Tests.Unit
              run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults-Ubuntu-DotNet6"
